

CREATE  TABLE USERS(
id            SERIAL       PRIMARY KEY,
email      VARCHAR(128) NOT NULL UNIQUE,
username   VARCHAR(128) NOT NULL UNIQUE,
password      VARCHAR(64) NOT NULL CONSTRAINT PASSWORD_LENGTH CHECK(char_length(password)>8),
created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
modified_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
user_verified BOOLEAN DEFAULT false,
USER_ROLE_TYPE_ID SMALLINT NOT NULL
);